### ISSUE TITLE
Crash when generating pdf

### ISSUE THREAD

**Issue by flokasper** [asyncapi/html-template#112]
#### Describe the bug

I am trying to generate pdf from the asyncapi.json using docker, rendering the html works perfectly but I have a crash when generating the pdf:
```
npm http fetch GET 200 https://registry.npmjs.org/@asyncapi%2fhtml-template 894ms
npm http fetch GET 200 https://registry.npmjs.org/@asyncapi/html-template/-/html-template-0.15.1.tgz 77ms
npm http fetch GET 304 https://registry.npmjs.org/rimraf 71ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz 38ms
npm http fetch GET 200 https://registry.npmjs.org/puppeteer 115ms
npm http fetch GET 200 https://registry.npmjs.org/puppeteer/-/puppeteer-5.4.0.tgz 75ms
npm http fetch GET 200 https://registry.npmjs.org/@asyncapi%2fgenerator-filters 712ms
npm http fetch GET 200 https://registry.npmjs.org/@asyncapi/generator-filters/-/generator-filters-1.1.0.tgz 56ms
npm http fetch GET 200 https://registry.npmjs.org/openapi-sampler 37ms
npm http fetch GET 200 https://registry.npmjs.org/markdown-it 44ms
npm http fetch GET 200 https://registry.npmjs.org/markdown-it/-/markdown-it-10.0.0.tgz 29ms
npm http fetch GET 200 https://registry.npmjs.org/openapi-sampler/-/openapi-sampler-1.0.0-beta.17.tgz 435ms
npm http fetch GET 304 https://registry.npmjs.org/entities 36ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/entities/-/entities-2.0.3.tgz 28ms
npm http fetch GET 200 https://registry.npmjs.org/json-pointer 39ms
npm http fetch GET 200 https://registry.npmjs.org/json-pointer/-/json-pointer-0.6.1.tgz 30ms
npm http fetch GET 200 https://registry.npmjs.org/foreach 33ms
npm http fetch GET 200 https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz 33ms
npm http fetch GET 200 https://registry.npmjs.org/https-proxy-agent 43ms
npm http fetch GET 200 https://registry.npmjs.org/proxy-from-env 74ms
npm http fetch GET 200 https://registry.npmjs.org/devtools-protocol 76ms
npm http fetch GET 200 https://registry.npmjs.org/pkg-dir 77ms
npm http fetch GET 200 https://registry.npmjs.org/unbzip2-stream 87ms
npm http fetch GET 200 https://registry.npmjs.org/progress 89ms
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 91ms
npm http fetch GET 200 https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-4.0.0.tgz 52ms
npm http fetch GET 200 https://registry.npmjs.org/extract-zip 119ms
npm http fetch GET 200 https://registry.npmjs.org/ws 147ms
npm http fetch GET 200 https://registry.npmjs.org/pkg-dir/-/pkg-dir-4.2.0.tgz 67ms
npm http fetch GET 200 https://registry.npmjs.org/proxy-from-env/-/proxy-from-env-1.1.0.tgz 71ms
npm http fetch GET 200 https://registry.npmjs.org/unbzip2-stream/-/unbzip2-stream-1.4.3.tgz 64ms
npm http fetch GET 200 https://registry.npmjs.org/progress/-/progress-2.0.3.tgz 63ms
npm http fetch GET 200 https://registry.npmjs.org/devtools-protocol/-/devtools-protocol-0.0.809251.tgz 75ms
npm http fetch GET 200 https://registry.npmjs.org/tar-fs/-/tar-fs-2.1.0.tgz 59ms
npm http fetch GET 200 https://registry.npmjs.org/extract-zip/-/extract-zip-2.0.1.tgz 39ms
npm http fetch GET 200 https://registry.npmjs.org/ws/-/ws-7.3.1.tgz 30ms
npm http fetch GET 200 https://registry.npmjs.org/yauzl 32ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2fyauzl 37ms
npm http fetch GET 200 https://registry.npmjs.org/yauzl/-/yauzl-2.10.0.tgz 25ms
npm http fetch GET 200 https://registry.npmjs.org/@types/yauzl/-/yauzl-2.9.1.tgz 38ms
npm http fetch GET 200 https://registry.npmjs.org/get-stream 720ms
npm http fetch GET 200 https://registry.npmjs.org/get-stream/-/get-stream-5.2.0.tgz 61ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2fnode 75ms
npm http fetch GET 200 https://registry.npmjs.org/@types/node/-/node-14.14.5.tgz 52ms
npm http fetch GET 200 https://registry.npmjs.org/pump 28ms
npm http fetch GET 200 https://registry.npmjs.org/pump/-/pump-3.0.0.tgz 30ms
npm http fetch GET 200 https://registry.npmjs.org/once 29ms
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream 45ms
npm http fetch GET 200 https://registry.npmjs.org/once/-/once-1.4.0.tgz 34ms
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.4.tgz 56ms
npm http fetch GET 200 https://registry.npmjs.org/wrappy 51ms
npm http fetch GET 200 https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz 31ms
npm http fetch GET 200 https://registry.npmjs.org/fd-slicer 26ms
npm http fetch GET 200 https://registry.npmjs.org/buffer-crc32 32ms
npm http fetch GET 200 https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.13.tgz 27ms
npm http fetch GET 200 https://registry.npmjs.org/fd-slicer/-/fd-slicer-1.1.0.tgz 33ms
npm http fetch GET 200 https://registry.npmjs.org/pend 45ms
npm http fetch GET 200 https://registry.npmjs.org/pend/-/pend-1.2.0.tgz 28ms
npm http fetch GET 200 https://registry.npmjs.org/agent-base 34ms
npm http fetch GET 200 https://registry.npmjs.org/agent-base/-/agent-base-5.1.1.tgz 32ms
npm http fetch GET 200 https://registry.npmjs.org/glob 41ms
npm http fetch GET 200 https://registry.npmjs.org/glob/-/glob-7.1.6.tgz 52ms
npm http fetch GET 200 https://registry.npmjs.org/fs.realpath 29ms
npm http fetch GET 200 https://registry.npmjs.org/inflight 31ms
npm http fetch GET 200 https://registry.npmjs.org/path-is-absolute 36ms
npm http fetch GET 200 https://registry.npmjs.org/inherits 48ms
npm http fetch GET 200 https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz 30ms
npm http fetch GET 200 https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz 27ms
npm http fetch GET 200 https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz 34ms
npm http fetch GET 200 https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz 51ms
npm http fetch GET 200 https://registry.npmjs.org/chownr 36ms
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 37ms
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 40ms
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic/-/mkdirp-classic-0.5.3.tgz 29ms
npm http fetch GET 200 https://registry.npmjs.org/tar-stream/-/tar-stream-2.1.4.tgz 35ms
npm http fetch GET 200 https://registry.npmjs.org/chownr/-/chownr-1.1.4.tgz 41ms
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 31ms
npm http fetch GET 200 https://registry.npmjs.org/bl 32ms
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 39ms
npm http fetch GET 200 https://registry.npmjs.org/bl/-/bl-4.0.3.tgz 28ms
npm http fetch GET 200 https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz 29ms
npm http fetch GET 200 https://registry.npmjs.org/fs-constants/-/fs-constants-1.0.0.tgz 44ms
npm http fetch GET 200 https://registry.npmjs.org/buffer 32ms
npm http fetch GET 200 https://registry.npmjs.org/buffer/-/buffer-5.6.1.tgz 52ms
npm http fetch GET 200 https://registry.npmjs.org/base64-js 32ms
npm http fetch GET 200 https://registry.npmjs.org/ieee754 42ms
npm http fetch GET 200 https://registry.npmjs.org/base64-js/-/base64-js-1.3.1.tgz 29ms
npm http fetch GET 200 https://registry.npmjs.org/ieee754/-/ieee754-1.1.13.tgz 39ms
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 22ms
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate 27ms
npm http fetch GET 200 https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz 31ms
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz 28ms
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 31ms
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz 32ms
npm http fetch GET 304 https://registry.npmjs.org/fsevents 43ms (from cache)

> puppeteer@5.4.0 install /usr/local/lib/node_modules/@asyncapi/generator/node_modules/puppeteer
> node install.js

Downloading Chromium r809590 - 129.6 Mb [====================] 100% 0.0s
Chromium (809590) downloaded to /usr/local/lib/node_modules/@asyncapi/generator/node_modules/puppeteer/.local-chromium/linux-809590
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @asyncapi/html-template@0.15.1
added 48 packages from 78 contributors in 16.523s

18 packages are looking for funding
  run `npm fund` for details

Something went wrong:
Error: Failed to launch the browser process! spawn /usr/local/lib/node_modules/@asyncapi/generator/node_modules/puppeteer/.local-chromium/linux-809590/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

#### How to Reproduce

```
docker run --rm -it \
    -v "interface:/data" \
    -v "output/asyncapi:/output" \
    asyncapi/generator:latest \
    -o /output \
    -p pdf=true \
    --force-write \
    /data/asyncapi.json \
    @asyncapi/html-template
```
If I remove -p pdf=true, it works

**Comment by derberg** [comment]
@flokasper looking at https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md I think it is caused by the fact that we use alpine in generator docker https://github.com/asyncapi/generator/blob/master/Dockerfile#L1

Some fix is described here https://github.com/puppeteer/puppeteer/issues/379#issuecomment-334447389 so we will have to check and update official docker image. Would be awesome if this is something you can test on your own first

**Comment by derberg** [comment]
@flokasper I just opened PRs to fix it
