### ISSUE TITLE
issue with node 15

### ISSUE THREAD

**Issue by eriadam** [asyncapi/html-template#143]
#### Describe the bug

I am unable to run the generator with v15.3.0 (with npm 7.0.14).
It works fine with v14.15.0.

```
> async-api-docs@1.0.0 build
> ./node_modules/.bin/ag ifc-pre-processor/asyncapi.yaml @asyncapi/html-template -o dist

Something went wrong:
TypeError: must call as: npm.load(callback)
    at Object.load (/usr/local/lib/node_modules/npm/lib/npm.js:129:13)
    at npmi (/Users/adameri/Developer/bimspot/async-api-docs/node_modules/npmi/npmi.js:189:9)
    at /Users/adameri/Developer/bimspot/async-api-docs/node_modules/@asyncapi/generator/lib/generator.js:377:7
npm ERR! code 1
npm ERR! path /Users/adameri/Developer/bimspot/async-api-docs
npm ERR! command failed
npm ERR! command sh -c ./node_modules/.bin/ag ifc-pre-processor/asyncapi.yaml @asyncapi/html-template -o dist
```

#### How to Reproduce

Install node 15, delete existing output folder, run generator.

#### Expected behavior

Docs are generated in the output folder

**Comment by derberg** [comment]
@eriadam at the moment we recommend downgrading npm to 6.13.7 because of the issue you mentioned. I will move this issue to the generator repository as the fix needs to be provided there. Can you please update the title that the issue is not really with the node version but npm (node 15 by default gets npm 7)?
