### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by mattias-persson** [asyncapi/html-template#401]
#### Describe the bug
`npx ag [my-schema].json @asyncapi/html-template -o docs--force-write` results in the following error: 
```
Something went wrong:
TypeError: Cannot read properties of null (reading 'useRef')
    at Object.useRef (/[path]/node_modules/@asyncapi/html-template/node_modules/use-resize-observer/node_modules/react/cjs/react.development.js:1630:21)
    at useResizeObserver (/[path]/node_modules/@asyncapi/html-template/node_modules/use-resize-observer/dist/bundle.cjs.js:115:27)
    at AsyncApiLayout (/[path]/node_modules/@asyncapi/html-template/node_modules/@asyncapi/react-component/src/containers/AsyncApi/Layout.tsx:30:36)
```

This seems to have appeared over night, it has worked previously.

#### How to Reproduce
Node v16.13.1.
@asyncapi/generator v1.9.14.
@asyncapi/html-template v1.9.14.

Tried with a bare minimum schema as well, no luck.

#### Expected behavior
The documentation should be generated.

**Comment by mattias-persson** [comment]
@magicmatatjahu Thanks a ton, that helped! Feel free to close the issue, unless you want to keep it open to track the actual issue.

**Comment by magicmatatjahu** [comment]
@mattias-persson No problem :) If you wanna still use the latest html-template (without specifying the version in cli), you should try to remove the `npx` cache by `rm -rf ~/.npm/_npx` - probably you have some incorrect installed deps, and then npx should fetch the latest (in proper way) version of template. I will close this one. Let me know if you will have similar problems.
