### ISSUE TITLE
[BUG] Error to generate asyncapi doc with version v2.3.12

### ISSUE THREAD

**Issue by eduherediaweb** [asyncapi/html-template#670]
### Describe the bug.

I obtain this error with the latest version v2.3.12 when I execute this:

`docker run --rm -it -v ${PWD}/resources/asyncapi:/app/asyncapi -v ${PWD}/api/asyncapi:/output \
asyncapi/generator:1.16.0 /app/asyncapi/returnUpdated.yml @asyncapi/html-template@v2.3.12 --force-write -o /output/html`

`Something went wrong:
/usr/local/lib/node_modules/@asyncapi/generator/node_modules/puppeteer-core/lib/cjs/puppeteer/util/disposable.js:9
Symbol.dispose ??= Symbol('dispose');
               ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Object.require.extensions.<computed> [as .js] (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/puppeteer-core/src/common/EventEmitter.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)`

With previous versions (for example v2.3.11) it works correctly.

### Expected behavior

`[BABEL] Note: The code generator has deoptimised the styling of /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/template/js/asyncapi-ui.min.js as it exceeds the max of 500KB.

Done! 
Check out your shiny new generated files at /output/html.`

### Screenshots

<img width="1661" alt="Captura de pantalla 2024-08-29 a las 11 23 19" src="https://github.com/user-attachments/assets/64d09e2e-d638-4e65-b8de-3aaac58b6932">

### How to Reproduce

1. Generate asynacpi doc with html template with v2.3.12

docker run --rm -it -v ${PWD}/resources/asyncapi:/app/asyncapi -v ${PWD}/api/asyncapi:/output \
asyncapi/generator:1.16.0 /app/asyncapi/returnUpdated.yml @asyncapi/html-template@v2.3.12 --force-write -o /output/html

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by derberg** [comment]
sorry about that, fix has been deployed -> https://github.com/asyncapi/html-template/pull/672#issuecomment-2324913576
thanks for letting us know

**Comment by eduherediaweb** [comment]
Thanks, with the version @asyncapi/html-template@v2.3.13 works correctly. Thanks!

![Screenshot from 2024-09-04 20-23-03](https://github.com/user-attachments/assets/643867c6-af8a-4b58-9285-f653e3d5cc51)
